// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbbgamjrpqeatrcfjtdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiYmdhbWpycHFlYXRyY2ZqdGRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMjEwMzgsImV4cCI6MjA3MDU5NzAzOH0.0cBE3MOIMSyy4lBU6W_peLTlUzojln81hDUbAX4JcWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});